server:
  address: 0.0.0.0
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
    application:
      name: upload-api

jwt:
  secret: TuClaveSuperSecreta1234567890123456


aws:
  accessKeyId: ACCESS_KEY
  secretAccessKey: SECRET_KEY

app:
  admin:
    username: admin
    password: admin_123
    role: ADMIN
  user:
    username: user
    password: admin_123
    role: USER